// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nbwzrfvxnztpbxwsyaqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5id3pyZnZ4bnp0cGJ4d3N5YXFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNDE3MjcsImV4cCI6MjA2NjgxNzcyN30.iLZfPGdROTcNQMgynxFcdNbTSUVheA8cr7bBQqsv2XY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});